### ISSUE TITLE
supporting receive with UDP and send with HTTP

### ISSUE THREAD

**Issue by fabware** [getsentry/sentry-relay-attic#1]
In multiple data-center setup, It would be more useful if the sending part is HTTP, which is much more reliable and more easy to do access control. Any thought about it?

I would be helpful if you can publish more information about features under development and features you are planning.

**Comment by dcramer** [comment]
I realize this ticket is 2 years old, so I'm just going to close it.

tl;dr Sentry no longer supports UDP, and HTTP (or some other socket) for the relay is clean enough.

**Comment by fabware** [comment]
Thanks for your reply.
