### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by ghost** [getsentry/sentry-relay-attic#5]
Hello,

Can you please tell me how to build this project ? I'm in Ubuntu system with golang installed.
I cloned this project in my home directory and when  I run make command inside it i get this message : 
go install: no install location for directory /root/sentry-relay outside GOPATH
	For more details see: go help gopath

I then export set gopath variable 
export GOPATH=$HOME/sentry-relay
and rebuid it but in vain, still have the same error.

Thanks in advance,

**Comment by mattrobenolt** [comment]
This hasn't been touched since 2014 and was never finished and isn't being used yet.

**Comment by ghost** [comment]
Is this project definitely abandoned ? or we still can hope that one day it will be finished and correctly operating ?

**Comment by mattrobenolt** [comment]
I mean, it might come back, but there are no immediate plans.
